"""Create transactions tables

Revision ID: 9e3725b9fd27
Revises:
Create Date: 2024-08-21 13:19:02.354297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e3725b9fd27'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS ivashko_schema')
    op.create_table('account_ivashko',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('balance', sa.BIGINT(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['ivashko_schema.users_ivashko.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='ivashko_schema'
    )
    op.create_table('transactions_ivashko',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.BIGINT(), nullable=False),
    sa.Column('type', sa.Enum('DEBIT', 'CREDIT', name='transactiontype'), nullable=False),
    sa.Column('balance_after', sa.BIGINT(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['ivashko_schema.account_ivashko.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='ivashko_schema'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions_ivashko', schema='ivashko_schema')
    op.drop_table('account_ivashko', schema='ivashko_schema')
    op.execute('DROP SCHEMA IF EXISTS ivashko_schema')
    # ### end Alembic commands ###
