version: '3'

services:
  app:
    container_name: 'transaction_service_ivashko'
    build:
      context: app/
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - ${SSH_KEY_PATH}/id_rsa:/root/.ssh/id_rsa
      - ${SSH_KEY_PATH}/id_rsa.pub:/root/.ssh/id_rsa.pub
    ports:
      - '28082:8082'
    command: sleep infinity
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    environment:
      - PYTHONPATH=/workspace/src
