apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.nameService | lower | replace " " "-" }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.nameContainer | lower | replace " " "-" }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.nameContainer | lower | replace " " "-" }}
    spec:
      containers:
        - name: {{ .Values.app.nameContainer | lower | replace " " "-" }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          env:
            - name: POSTGRES_HOST
              value: {{ .Values.postgres.host }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secretName }}
                  key: {{ .Values.postgres.userKey }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secretName }}
                  key: {{ .Values.postgres.passwordKey }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.dbName }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            requests:
              cpu: {{ .Values.app.resources.requests.cpu }}
            limits:
              cpu: {{ .Values.app.resources.limits.cpu }}
