apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.nameService | lower | replace " " "-" }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.app.nameContainer }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
