apiVersion: apps/v1
kind: Deployment
metadata:
  name: ivashko-transaction-deployment
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
    spec:
      containers:
      - name: transaction-service
        image: merewhale/transactions-service
        env:
        - name: PYTHONPATH
          value: /workspace/src/app
        - name: POSTGRES_HOST
          value: http://postgres-service:5432
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        - name: POSTGRES_DB
          value: iivashko
        ports:
        - containerPort: 8002

